# Configuration for CI build at https://travis-ci.org/hsz/idea-nodesecurity

language: java

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=2017.3.2
  - IDEA_VERSION=2017.2
  - IDEA_VERSION=2017.1.5
  - IDEA_VERSION=2016.3.7
  - IDEA_VERSION=2016.2.5
  - IDEA_VERSION=2016.1.4

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls
